// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HBpmnDesigner: typeof import('./src/components/HBpmnDesigner.vue')['default']
    HBpmnDesignerToolbar: typeof import('./src/components/HBpmnDesignerToolbar.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QBtnDropdown: typeof import('quasar')['QBtnDropdown']
    QBtnGroup: typeof import('quasar')['QBtnGroup']
    QCard: typeof import('quasar')['QCard']
    QFile: typeof import('quasar')['QFile']
    QIcon: typeof import('quasar')['QIcon']
    QList: typeof import('quasar')['QList']
    QSeparator: typeof import('quasar')['QSeparator']
    QToolbar: typeof import('quasar')['QToolbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
