// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HBehaviorCaptcha: typeof import('./src/components/widgets/captcha/HBehaviorCaptcha.vue')['default']
    HBehaviorCaptchaFeedback: typeof import('./src/components/widgets/captcha/HBehaviorCaptchaFeedback.vue')['default']
    HContainer: typeof import('./src/components/library/HContainer/HContainer.vue')['default']
    HGraphicCaptcha: typeof import('./src/components/widgets/captcha/HGraphicCaptcha.vue')['default']
    HJigsawCaptcha: typeof import('./src/components/widgets/captcha/HJigsawCaptcha.vue')['default']
    HOverlay: typeof import('./src/components/library/HOverlay/HOverlay.vue')['default']
    HSettingSwitch: typeof import('./src/components/library/HSwitch/HSettingSwitch.vue')['default']
    HSheet: typeof import('./src/components/library/HSheet/HSheet.vue')['default']
    HTable: typeof import('./src/components/library/HTable/HTable.vue')['default']
    HTextDivider: typeof import('./src/components/library/HDivider/HTextDivider.vue')['default']
    HTooltipButton: typeof import('./src/components/library/HButton/HTooltipButton.vue')['default']
    HVerticalDivider: typeof import('./src/components/library/HDivider/HVerticalDivider.vue')['default']
    HWordClickCaptcha: typeof import('./src/components/widgets/captcha/HWordClickCaptcha.vue')['default']
    Index: typeof import('./src/components/library/HLabel/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
