/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HBehaviorCaptcha: typeof import('./src/components/widgets/captcha/HBehaviorCaptcha.vue')['default']
    HBehaviorCaptchaBackground: typeof import('./src/components/widgets/captcha/HBehaviorCaptchaBackground.vue')['default']
    HBehaviorCaptchaControl: typeof import('./src/components/widgets/captcha/HBehaviorCaptchaControl.vue')['default']
    HBehaviorCaptchaFeedback: typeof import('./src/components/widgets/captcha/HBehaviorCaptchaFeedback.vue')['default']
    HButton: typeof import('./src/components/library/HButton/HButton.vue')['default']
    HDictionarySelect: typeof import('./src/components/business/form/HDictionarySelect.vue')['default']
    HGraphicCaptcha: typeof import('./src/components/widgets/captcha/HGraphicCaptcha.vue')['default']
    HHorizontalLabel: typeof import('./src/components/library/HLabel/HHorizontalLabel.vue')['default']
    HJigsawCaptcha: typeof import('./src/components/widgets/captcha/HJigsawCaptcha.vue')['default']
    HLabel: typeof import('./src/components/library/HLabel/HLabel.vue')['default']
    HLayout: typeof import('./src/components/library/HLayout/HLayout.vue')['default']
    HOverlay: typeof import('./src/components/library/HOverlay/HOverlay.vue')['default']
    HSettingSwitch: typeof import('./src/components/library/HSwitch/HSettingSwitch.vue')['default']
    HSheet: typeof import('./src/components/library/HSheet/HSheet.vue')['default']
    HSwitch: typeof import('./src/components/library/HSwitch/HSwitch.vue')['default']
    HTable: typeof import('./src/components/library/HTable/HTable.vue')['default']
    HTableItemEditor: typeof import('./src/components/business/form/HTableItemEditor.vue')['default']
    HTextDivider: typeof import('./src/components/library/HDivider/HTextDivider.vue')['default']
    HTextField: typeof import('./src/components/library/HTextField/HTextField.vue')['default']
    HVerticalDivider: typeof import('./src/components/library/HDivider/HVerticalDivider.vue')['default']
    HWordClickCaptcha: typeof import('./src/components/widgets/captcha/HWordClickCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
