/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/components/error/403.vue')['default']
    404: typeof import('./../src/components/error/404.vue')['default']
    500: typeof import('./../src/components/error/500.vue')['default']
    HAppAnnouncementNotification: typeof import('./../src/components/layouts/common/header/HAppAnnouncementNotification.vue')['default']
    HAppBackHomeControl: typeof import('./../src/components/layouts/common/header/HAppBackHomeControl.vue')['default']
    HAppBreadcrumbs: typeof import('./../src/components/layouts/common/header/HAppBreadcrumbs.vue')['default']
    HAppContainer: typeof import('./../src/components/layouts/common/HAppContainer.vue')['default']
    HAppDialogueNotification: typeof import('./../src/components/layouts/common/header/HAppDialogueNotification.vue')['default']
    HAppHeader: typeof import('./../src/components/layouts/common/header/HAppHeader.vue')['default']
    HAppLeftDrawer: typeof import('./../src/components/layouts/default/HAppLeftDrawer.vue')['default']
    HAppLeftDrawerControl: typeof import('./../src/components/layouts/common/header/HAppLeftDrawerControl.vue')['default']
    HAppMenu: typeof import('./../src/components/layouts/default/HAppMenu.vue')['default']
    HAppMenuItems: typeof import('./../src/components/layouts/common/HAppMenuItems.vue')['default']
    HAppMessageActions: typeof import('./../src/components/layouts/common/header/HAppMessageActions.vue')['default']
    HAppRightDrawer: typeof import('./../src/components/layouts/default/HAppRightDrawer.vue')['default']
    HAppRightDrawerControl: typeof import('./../src/components/layouts/common/header/HAppRightDrawerControl.vue')['default']
    HAppTabsView: typeof import('./../src/components/layouts/common/header/HAppTabsView.vue')['default']
    HAppToolbarActions: typeof import('./../src/components/layouts/common/header/HAppToolbarActions.vue')['default']
    HAppWidgetActions: typeof import('./../src/components/layouts/common/header/HAppWidgetActions.vue')['default']
    HAuditCondition: typeof import('./../src/components/library/HAuthorize/HAuditCondition.vue')['default']
    HAuthorizeHeader: typeof import('./../src/components/library/HAuthorize/HAuthorizeHeader.vue')['default']
    HAuthorizeLayout: typeof import('./../src/components/library/HAuthorize/HAuthorizeLayout.vue')['default']
    HAuthorizeList: typeof import('./../src/components/library/HAuthorize/HAuthorizeList.vue')['default']
    HBehaviorCaptcha: typeof import('./../src/components/library/HCaptcha/HBehaviorCaptcha.vue')['default']
    HBehaviorCaptchaBackground: typeof import('./../src/components/library/HCaptcha/HBehaviorCaptchaBackground.vue')['default']
    HBehaviorCaptchaControl: typeof import('./../src/components/library/HCaptcha/HBehaviorCaptchaControl.vue')['default']
    HBehaviorCaptchaFeedback: typeof import('./../src/components/library/HCaptcha/HBehaviorCaptchaFeedback.vue')['default']
    HBooleanColumn: typeof import('./../src/components/library/HTable/HBooleanColumn.vue')['default']
    HCenterFormLayout: typeof import('./../src/components/layouts/forms/HCenterFormLayout.vue')['default']
    HChunkUploader: typeof import('./../src/components/library/HUploader/HChunkUploader.vue')['default']
    HColumnFormLayout: typeof import('./../src/components/layouts/forms/HColumnFormLayout.vue')['default']
    HComplianceCondition: typeof import('./../src/components/library/HAuthorize/HComplianceCondition.vue')['default']
    HDeleteButton: typeof import('./../src/components/library/HTable/HDeleteButton.vue')['default']
    HDenseIconButton: typeof import('./../src/components/library/HTable/HDenseIconButton.vue')['default']
    HDetailContainer: typeof import('./../src/components/layouts/forms/HDetailContainer.vue')['default']
    HDictionarySelect: typeof import('./../src/components/library/HSelect/HDictionarySelect.vue')['default']
    HEditButton: typeof import('./../src/components/library/HTable/HEditButton.vue')['default']
    HErrorLayout: typeof import('./../src/components/layouts/forms/HErrorLayout.vue')['default']
    HFormSkeleton: typeof import('./../src/components/library/HSkeleton/HFormSkeleton.vue')['default']
    HFullWidthLayout: typeof import('./../src/components/layouts/forms/HFullWidthLayout.vue')['default']
    HGrantTypeColumn: typeof import('./../src/components/library/HTable/HGrantTypeColumn.vue')['default']
    HGraphicCaptcha: typeof import('./../src/components/library/HCaptcha/HGraphicCaptcha.vue')['default']
    HHttpMethodAvatar: typeof import('./../src/components/library/HAuthorize/HHttpMethodAvatar.vue')['default']
    HInfoButton: typeof import('./../src/components/library/HTable/HInfoButton.vue')['default']
    HJigsawCaptcha: typeof import('./../src/components/library/HCaptcha/HJigsawCaptcha.vue')['default']
    HOptionField: typeof import('./../src/components/library/HSelect/HOptionField.vue')['default']
    HReservedColumn: typeof import('./../src/components/library/HTable/HReservedColumn.vue')['default']
    HSendMessageField: typeof import('./../src/components/library/HMessage/HSendMessageField.vue')['default']
    HSettingContainer: typeof import('./../src/components/layouts/settings/HSettingContainer.vue')['default']
    HSettingMenu: typeof import('./../src/components/layouts/settings/HSettingMenu.vue')['default']
    HSettingSwitch: typeof import('./../src/components/layouts/settings/HSettingSwitch.vue')['default']
    HSimpleCenterFormLayout: typeof import('./../src/components/layouts/forms/HSimpleCenterFormLayout.vue')['default']
    HSimpleUploader: typeof import('./../src/components/library/HUploader/HSimpleUploader.vue')['default']
    HStatusColumn: typeof import('./../src/components/library/HTable/HStatusColumn.vue')['default']
    HSwaggerColumn: typeof import('./../src/components/library/HTable/HSwaggerColumn.vue')['default']
    HTable: typeof import('./../src/components/library/HTable/HTable.vue')['default']
    HTableAction: typeof import('./../src/components/library/HTable/HTableAction.vue')['default']
    HToggleField: typeof import('./../src/components/library/HSelect/HToggleField.vue')['default']
    HUserAvatar: typeof import('./../src/components/layouts/common/avatar/HUserAvatar.vue')['default']
    HWordClickCaptcha: typeof import('./../src/components/library/HCaptcha/HWordClickCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
