export type {
  Entity,
  Conditions,
  Page,
  Sort,
  Tree,
  ValidateResult,
  AxiosTransform,
  AxiosHttpResult,
  AxiosProgressEvent,
  RequestOptions,
  RetryRequest,
  HttpConfig,
  HttpResult,
  HttpMethod,
  OAuth2Token,
  OAuth2IdToken,
  QBaseDataItem,
  QTableSeparatorProps,
  QTableColumnProps,
  QTablePaginationProps,
  QTableOnRequestProps,
  QTableOnRequestParameter,
  QUploaderInfo,
  QNotifyPosition
} from '@herodotus/core';
export type {
  BaseEntity,
  BaseSysEntity,
  JigsawCaptcha,
  WordClickCaptcha,
  GraphicCaptcha,
  Coordinate,
  Session,
  BehaviorCaptchaCategory,
  CaptchaResource,
  CaptchaData,
  ConstantDictionary,
  SignInErrorStatus,
  SysPermissionEntity,
  SysPermissionConditions,
  SysPermissionProps,
  SysRoleEntity,
  SysRoleConditions,
  SysRoleProps,
  SysUserEntity,
  SysUserConditions,
  SysUserProps,
  SysAttributeEntity,
  SysAttributeConditions,
  SysAttributeProps,
  SysDefaultRoleEntity,
  SysDefaultRoleConditions,
  SysDefaultRoleProps,
  SysElementEntity,
  SysElementConditions,
  SysElementProps,
  SysEmployeeEntity,
  SysEmployeeConditions,
  SysEmployeeProps,
  SysEmployeeAllocatable,
  SysOrganizationEntity,
  SysOrganizationConditions,
  SysOrganizationProps,
  SysDepartmentEntity,
  SysDepartmentConditions,
  SysDepartmentProps,
  DatabaseInstanceEntity,
  DatabaseInstanceConditions,
  DatabaseInstanceProps,
  DatabaseCatalogEntity,
  DatabaseCatalogConditions,
  DatabaseCatalogProps,
  DatabaseAccountEntity,
  DatabaseAccountConditions,
  DatabaseAccountProps,
  AssetServerEntity,
  AssetServerConditions,
  AssetServerProps,
  AssetApplicationEntity,
  AssetApplicationConditions,
  AssetApplicationProps,
  OAuth2AuthorizationEntity,
  OAuth2AuthorizationConditions,
  OAuth2ApplicationProps,
  OAuth2ApplicationEntity,
  OAuth2ApplicationConditions,
  OAuth2ScopeEntity,
  OAuth2ScopeConditions,
  OAuth2ScopeProps,
  OAuth2ComplianceEntity,
  OAuth2ComplianceConditions,
  OAuth2ComplianceProps,
  OAuth2DeviceEntity,
  OAuth2DeviceConditions,
  OAuth2DeviceProps,
  OAuth2ProductEntity,
  OAuth2ProductConditions,
  OAuth2ProductProps,
  OAuth2ScopeAssignedBody,
  OAuth2PermissionBody,
  DialogueContactEntity,
  DialogueContactConditions,
  DialogueContactProps,
  DialogueDetailEntity,
  DialogueDetailConditions,
  DialogueDetailProps,
  NotificationEntity,
  NotificationConditions,
  NotificationProps,
  ExtendedTaskEntity,
  ExtendedTaskConditions,
  ExtendedTaskProps,
  SysTenantDataSourceEntity,
  SysTenantDataSourceConditions,
  SysTenantDataSourceProps
} from '@herodotus/apis';

export type {
  BucketDomain,
  BucketDomainProps,
  BucketDomainConditions,
  ObjectDomain,
  ObjectDomainProps,
  ObjectDomainConditions,
  ObjectListingDomain,
  CreateMultipartUploadBusiness,
  BucketSettingBusiness,
  DeleteObjectDomain,
  ObjectSettingBusiness,
  ObjectLockConfigurationDomain
} from '@herodotus/oss-apis';

export type {
  BpmnQueryByGetService,
  BpmnListEntity,
  BpmnListQueryParams,
  BpmnDeleteQueryParams,
  BpmnUnionPathParams,
  BpmnSortable,
  DeploymentEntity,
  DeploymentQueryParams,
  DeploymentSortBy,
  DeploymentDeleteQueryParams,
  ProcessDefinitionEntity,
  ProcessDefinitionQueryParams,
  ProcessDefinitionSortBy,
  ProcessDefinitionDeleteQueryParams,
  XmlEntity,
  ProcessInstanceEntity,
  ProcessInstanceQueryParams,
  ProcessInstanceSortBy,
  ProcessInstanceDeleteQueryParams,
  TaskEntity,
  TaskQueryParams,
  TaskSortBy
} from '@herodotus/bpmn-apis';

export type { EChartsOption, EChartsCoreOption } from 'echarts';

export type { QTableProps, QTree, QUploaderFactoryObject } from 'quasar';

export type { SweetAlertIcon, SweetAlertResult } from 'sweetalert2';
