// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HDynamicForms: typeof import('./src/components/HDynamicForms.vue')['default']
    HWidgetPanel: typeof import('./src/components/panels/HWidgetPanel.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QDrawer: typeof import('quasar')['QDrawer']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QLayout: typeof import('quasar')['QLayout']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
