/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HCanvasContainer: typeof import('./src/components/canvas/HCanvasContainer.vue')['default']
    HCanvasElement: typeof import('./src/components/canvas/HCanvasElement.vue')['default']
    HCanvasLayout: typeof import('./src/components/library/HCanvasLayout.vue')['default']
    HConditionVariable: typeof import('./src/components/property-elements/HConditionVariable.vue')['default']
    HDatePanel: typeof import('./src/components/property-panels/HDatePanel.vue')['default']
    HDynamicForms: typeof import('./src/components/HDynamicForms.vue')['default']
    HExpansionItem: typeof import('./src/components/library/HExpansionItem.vue')['default']
    HFormInformation: typeof import('./src/components/canvas-toolbar/HFormInformation.vue')['default']
    HFormPreviewDialog: typeof import('./src/components/canvas-toolbar/HFormPreviewDialog.vue')['default']
    HFormUploadDialog: typeof import('./src/components/canvas-toolbar/HFormUploadDialog.vue')['default']
    HPasswordPanel: typeof import('./src/components/property-panels/HPasswordPanel.vue')['default']
    HPropertyPanel: typeof import('./src/components/canvas-panel/HPropertyPanel.vue')['default']
    HSheetPanel: typeof import('./src/components/property-panels/HSheetPanel.vue')['default']
    HTextareaPanel: typeof import('./src/components/property-panels/HTextareaPanel.vue')['default']
    HTextFieldPanel: typeof import('./src/components/property-panels/HTextFieldPanel.vue')['default']
    HTimePanel: typeof import('./src/components/property-panels/HTimePanel.vue')['default']
    HWidgetPanel: typeof import('./src/components/canvas-panel/HWidgetPanel.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDialog: typeof import('quasar')['QDialog']
    QDrawer: typeof import('quasar')['QDrawer']
    QExpansionItem: typeof import('quasar')['QExpansionItem']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QPopupEdit: typeof import('quasar')['QPopupEdit']
    QSeparator: typeof import('quasar')['QSeparator']
    QSpace: typeof import('quasar')['QSpace']
    QTab: typeof import('quasar')['QTab']
    QTable: typeof import('quasar')['QTable']
    QTabPanel: typeof import('quasar')['QTabPanel']
    QTabPanels: typeof import('quasar')['QTabPanels']
    QTabs: typeof import('quasar')['QTabs']
    QTd: typeof import('quasar')['QTd']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    QTr: typeof import('quasar')['QTr']
  }
}
