// Generated by 'unplugin-auto-import'
export {}
declare global {
  const useDialogPluginComponent: typeof import('quasar')['useDialogPluginComponent']
  const useFormChild: typeof import('quasar')['useFormChild']
  const useMeta: typeof import('quasar')['useMeta']
  const useQuasar: typeof import('quasar')['useQuasar']
}
