// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QDate: typeof import('quasar')['QDate']
    QIcon: typeof import('quasar')['QIcon']
    QInnerLoading: typeof import('quasar')['QInnerLoading']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QPagination: typeof import('quasar')['QPagination']
    QPopupProxy: typeof import('quasar')['QPopupProxy']
    QSelect: typeof import('quasar')['QSelect']
    QSeparator: typeof import('quasar')['QSeparator']
    QTime: typeof import('quasar')['QTime']
    QToggle: typeof import('quasar')['QToggle']
    QTooltip: typeof import('quasar')['QTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
