/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDate: typeof import('quasar')['QDate']
    QDialog: typeof import('quasar')['QDialog']
    QIcon: typeof import('quasar')['QIcon']
    QInnerLoading: typeof import('quasar')['QInnerLoading']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QPagination: typeof import('quasar')['QPagination']
    QPopupProxy: typeof import('quasar')['QPopupProxy']
    QSelect: typeof import('quasar')['QSelect']
    QSeparator: typeof import('quasar')['QSeparator']
    QSpace: typeof import('quasar')['QSpace']
    QSpinnerDots: typeof import('quasar')['QSpinnerDots']
    QTime: typeof import('quasar')['QTime']
    QToggle: typeof import('quasar')['QToggle']
    QTooltip: typeof import('quasar')['QTooltip']
    QTree: typeof import('quasar')['QTree']
  }
}
